Update patch set 1
Patch Set 1: Verified+1 Code-Review+2

Hello, Mr. Adeel
this is sync patch with only NUI in Samsung/TizenFX.
I tried to merge all tizenfx (from Samsung/TizenFX to dalihub) but I got failed with the following MSG. I think you have force push permission, so please do sync work.
thank you.

Error msg =>
ssong2yo@ssong2yo-ubuntu:~/additionalHDD1TB/git/dalihub/TizenFX$ git push origin HEAD:refs/for/devel/master
Counting objects: 103, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (43/43), done.
Writing objects: 100% (103/103), 23.36 KiB | 0 bytes/s, done.
Total 103 (delta 80), reused 81 (delta 60)
remote: Resolving deltas: 100% (80/80)
remote: Processing changes: refs: 1, done    
remote: ERROR: commit 077aa04: email address 35090305+younghajung@users.noreply.github.com is not registered in your account, and you lack 'forge committer' permission.
remote: The following addresses are currently registered:
remote:    dongsug.song@samsung.com
remote: To register an email address, visit:
remote: https://review.gerrithub.io/settings#EmailAddresses
remote: 
remote: 
To ssh://dongsug-song@review.gerrithub.io:29418/dalihub/TizenFX
 ! [remote rejected] HEAD -> refs/for/devel/master (commit 077aa04: invalid committer)
error: failed to push some refs to 'ssh://dongsug-song@review.gerrithub.io:29418/dalihub/TizenFX'

Patch-set: 1
Reviewer: Gerrit User 1007416 <1007416@d5d70762-12d0-45a1-890d-524b12d3f735>
Reviewer: Gerrit User 1014637 <1014637@d5d70762-12d0-45a1-890d-524b12d3f735>
Reviewer: Gerrit User 1013729 <1013729@d5d70762-12d0-45a1-890d-524b12d3f735>
Reviewer: Gerrit User 1014618 <1014618@d5d70762-12d0-45a1-890d-524b12d3f735>
Reviewer: Gerrit User 1014229 <1014229@d5d70762-12d0-45a1-890d-524b12d3f735>
Reviewer: Gerrit User 1013547 <1013547@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=+2
Label: Verified=+1